Repository DBL-App-development-2023-G7/musicmap, pull requests merged in 2023-04, with the labels that each got.

#57 Do location permission request in HomeActivity
  app/src/main/java/com/example/musicmap/screens/main/HomeActivity.java
Labels: enhancement

#59 Artist data map
  app/src/main/java/com/example/musicmap/feed/Song.java
  app/src/main/java/com/example/musicmap/screens/map/ArtistDataMapFragment.java
  app/src/main/java/com/example/musicmap/screens/map/MapFragment.java
  app/src/main/java/com/example/musicmap/user/Artist.java
  app/src/main/java/com/example/musicmap/user/ArtistData.java
  app/src/test/java/com/example/musicmap/user/ArtistDataTest.java
Labels: enhancement

#66 Profile for all users
  app/src/main/java/com/example/musicmap/screens/main/HomeActivity.java
  app/src/main/java/com/example/musicmap/screens/profile/ProfileActivity.java
  app/src/main/java/com/example/musicmap/screens/profile/ProfilePageFragment.java
  app/src/main/java/com/example/musicmap/screens/settings/SettingsActivity.java
  app/src/main/java/com/example/musicmap/util/Constants.java
  app/src/main/java/com/example/musicmap/util/ui/FragmentUtil.java
  app/src/main/res/layout/fragment_profile_page.xml
Labels: enhancement

#71 Fix bugs on post fragment
  app/src/main/java/com/example/musicmap/screens/main/PostFragment.java
Labels: bug

#74 Fix NPE when spamming between map and feed
  app/src/main/java/com/example/musicmap/screens/map/PostMapFragment.java
Labels: bug

#72 MusicMemoryScreen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
  app/src/main/java/com/example/musicmap/screens/main/HomeActivity.java
  app/src/main/java/com/example/musicmap/screens/main/MusicMemoryActivity.java
  app/src/main/java/com/example/musicmap/screens/main/MusicMemoryFragment.java
  app/src/main/java/com/example/musicmap/screens/main/SpotifyWidgetFragment.java
  app/src/main/java/com/example/musicmap/screens/map/MusicMemoryMapFragment.java
  app/src/main/java/com/example/musicmap/util/Constants.java
  app/src/main/java/com/example/musicmap/util/ui/FragmentUtil.java
  app/src/main/res/drawable/appbar_rounded.xml
  app/src/main/res/drawable/circular.xml
  app/src/main/res/layout-land/fragment_register.xml
  app/src/main/res/layout/activity_music_memory.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_music_memory.xml
  app/src/main/res/layout/fragment_spotify_widget.xml
  app/src/main/res/layout/spotify_playback_widget_layout.xml
  app/src/main/res/navigation/nav_mm.xml
  app/src/main/res/values/ui_strings.xml
Labels: enhancement

#73 Minor bug fixes
  app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
  app/src/main/java/com/example/musicmap/screens/main/FeedFragment.java
  app/src/main/java/com/example/musicmap/screens/settings/SettingsActivity.java
Labels: bug

#78 Post current song
  app/src/main/java/com/example/musicmap/screens/main/PostFragment.java
  app/src/main/java/com/example/musicmap/util/ui/ImageUtils.java
Labels: enhancement

#76 Move spotify connection to settings
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/musicmap/screens/main/HomeActivity.java
  app/src/main/java/com/example/musicmap/screens/main/PostFragment.java
  app/src/main/java/com/example/musicmap/screens/settings/ConnectionSettingsFragment.java
  app/src/main/java/com/example/musicmap/screens/settings/SettingsActivity.java
  app/src/main/java/com/example/musicmap/util/spotify/SpotifyAuthActivity.java
  app/src/main/res/values/error_strings.xml
  app/src/main/res/xml/connection_preferences.xml
Labels: enhancement

#80 Allow for null on feedback preview uri, give error message
  app/src/main/java/com/example/musicmap/feed/Song.java
  app/src/main/java/com/example/musicmap/screens/main/SpotifyWidgetFragment.java
Labels: bug

#84 Open music memory when clicked on map
  app/src/main/java/com/example/musicmap/util/map/MusicMemoryOverlay.java
  app/src/main/java/com/example/musicmap/util/map/PostOverlay.java
Labels: enhancement

#90 Fix switching bug
  app/src/main/java/com/example/musicmap/screens/verification/VerificationActivity.java
Labels: bug

#93 Queries clean up
  app/checkstyle/checkstyle.xml
  app/src/androidTest/java/com/groupseven/musicmap/util/TaskUtilTest.java
  app/src/main/java/com/groupseven/musicmap/screens/main/artist/ArtistDataMapFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/artist/ArtistDataMostPlayedSongsFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/feed/FeedFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/map/PostMapFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/view/MusicMemoryFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/view/MusicMemoryMapFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/profile/ProfilePageFragment.java
  app/src/main/java/com/groupseven/musicmap/util/TaskUtil.java
  app/src/main/java/com/groupseven/musicmap/util/firebase/AuthSystem.java
  app/src/main/java/com/groupseven/musicmap/util/firebase/Queries.java
  app/src/main/java/com/groupseven/musicmap/util/regex/InputChecker.java
Labels: enhancement

#96 Actions cleanup
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/create/PostFragment.java
  app/src/main/java/com/groupseven/musicmap/util/firebase/Actions.java
  app/src/main/res/values/error_strings.xml
Labels: enhancement

#108 Cleanup AuthSystem
  app/src/androidTest/java/com/groupseven/musicmap/util/firebase/ActionsTest.java
  app/src/androidTest/java/com/groupseven/musicmap/util/firebase/AuthSystemTest.java
  app/src/androidTest/java/com/groupseven/musicmap/util/firebase/QueriesTest.java
  app/src/main/java/com/groupseven/musicmap/firebase/Session.java
  app/src/main/java/com/groupseven/musicmap/models/Post.java
  app/src/main/java/com/groupseven/musicmap/screens/auth/LoginFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/auth/RegisterFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/view/MusicMemoryFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/profile/ProfilePageFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/settings/AccountSettingsFragment.java
  app/src/main/java/com/groupseven/musicmap/util/adapters/FeedAdapter.java
  app/src/main/java/com/groupseven/musicmap/util/firebase/AuthSystem.java
  app/src/main/java/com/groupseven/musicmap/util/ui/ChangeEmailDialogFragment.java
  app/src/main/java/com/groupseven/musicmap/util/ui/ChangePasswordDialogFragment.java
  app/src/main/java/com/groupseven/musicmap/util/ui/ChangeUsernameDialogFragment.java
  app/src/main/java/com/groupseven/musicmap/util/ui/DeleteAccountDialogFragment.java
  app/src/main/res/values/error_strings.xml
Labels: enhancement

#113 Improve argument passing between screens
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/view/MusicMemoryActivity.java
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/view/MusicMemoryFragment.java
  app/src/main/java/com/groupseven/musicmap/screens/main/musicmemory/view/MusicMemoryMapFragment.java
  app/src/main/res/layout/activity_music_memory.xml
  app/src/main/res/layout/fragment_music_memory.xml
  app/src/main/res/values/error_strings.xml
Labels: enhancement

#121 Fixed the register functionality
  app/src/main/java/com/groupseven/musicmap/screens/auth/RegisterFragment.java
Labels: enhancement, priority: high

#120 Last fixes
  app/src/main/java/com/groupseven/musicmap/screens/auth/RegisterArtistFragment.java
  app/src/main/res/values/artist_strings.xml
Labels: enhancement, priority: low

#107 ReadMe
  README.md
Labels: enhancement, priority: high
